name: my_media_app
description: A Social Media App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  fluttertoast: ^8.0.9
  firebase_auth: ^4.6.0
  firebase_core: ^2.3.0
  firebase_database: ^10.0.6
  firebase_storage: ^11.0.6
  image_picker: ^0.8.5+3
  persistent_bottom_nav_bar: ^5.0.2
  flutter_svg: ^2.0.5
  navigator: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SF-Pro-Display-Bold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
    - family: SF-Pro-Display-Regular
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family:  SF-Pro-Display-Light
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light.otf
    - family:  SF-Pro-Display-Medium
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
