// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5kk9g9Ue616jKoWZi3I4-__bL2v3kcGM',
    appId: '1:364334410229:web:b6c9c20bc258eb7dedd8bc',
    messagingSenderId: '364334410229',
    projectId: 'my-media-app-28ad3',
    authDomain: 'my-media-app-28ad3.firebaseapp.com',
    databaseURL: 'https://my-media-app-28ad3-default-rtdb.firebaseio.com',
    storageBucket: 'my-media-app-28ad3.appspot.com',
    measurementId: 'G-7MMFFT1PVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnDbnZvYa-pqJhg-9UYGkfJpvoMfZzQvQ',
    appId: '1:364334410229:android:62cf5205cc8a158dedd8bc',
    messagingSenderId: '364334410229',
    projectId: 'my-media-app-28ad3',
    databaseURL: 'https://my-media-app-28ad3-default-rtdb.firebaseio.com',
    storageBucket: 'my-media-app-28ad3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0-sHOmK5iq9DgQQAP8AVjKpZK9-4WE3A',
    appId: '1:364334410229:ios:478e9d4ccaf8ca4fedd8bc',
    messagingSenderId: '364334410229',
    projectId: 'my-media-app-28ad3',
    databaseURL: 'https://my-media-app-28ad3-default-rtdb.firebaseio.com',
    storageBucket: 'my-media-app-28ad3.appspot.com',
    iosClientId:
        '364334410229-2n81ulh01mve0m0juoloijr263gbpqr2.apps.googleusercontent.com',
    iosBundleId: 'com.thesaurhub.mymediaapp',
  );
}
